# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Parallel-Computing-Projects-master\Project3\cs426_project3_code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Parallel-Computing-Projects-master\Project3\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Parallel-Computing-Projects-master\Project3\build\CMakeFiles C:\Parallel-Computing-Projects-master\Project3\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Parallel-Computing-Projects-master\Project3\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lbp_seq

# Build rule for target.
lbp_seq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lbp_seq
.PHONY : lbp_seq

# fast build rule for target.
lbp_seq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_seq.dir\build.make CMakeFiles/lbp_seq.dir/build
.PHONY : lbp_seq/fast

#=============================================================================
# Target rules for targets named lbp_omp

# Build rule for target.
lbp_omp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lbp_omp
.PHONY : lbp_omp

# fast build rule for target.
lbp_omp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_omp.dir\build.make CMakeFiles/lbp_omp.dir/build
.PHONY : lbp_omp/fast

#=============================================================================
# Target rules for targets named IO_test

# Build rule for target.
IO_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 IO_test
.PHONY : IO_test

# fast build rule for target.
IO_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IO_test.dir\build.make CMakeFiles/IO_test.dir/build
.PHONY : IO_test/fast

IO_test.obj: IO_test.c.obj
.PHONY : IO_test.obj

# target to build an object file
IO_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IO_test.dir\build.make CMakeFiles/IO_test.dir/IO_test.c.obj
.PHONY : IO_test.c.obj

IO_test.i: IO_test.c.i
.PHONY : IO_test.i

# target to preprocess a source file
IO_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IO_test.dir\build.make CMakeFiles/IO_test.dir/IO_test.c.i
.PHONY : IO_test.c.i

IO_test.s: IO_test.c.s
.PHONY : IO_test.s

# target to generate assembly for a file
IO_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IO_test.dir\build.make CMakeFiles/IO_test.dir/IO_test.c.s
.PHONY : IO_test.c.s

lbp_omp.obj: lbp_omp.c.obj
.PHONY : lbp_omp.obj

# target to build an object file
lbp_omp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_omp.dir\build.make CMakeFiles/lbp_omp.dir/lbp_omp.c.obj
.PHONY : lbp_omp.c.obj

lbp_omp.i: lbp_omp.c.i
.PHONY : lbp_omp.i

# target to preprocess a source file
lbp_omp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_omp.dir\build.make CMakeFiles/lbp_omp.dir/lbp_omp.c.i
.PHONY : lbp_omp.c.i

lbp_omp.s: lbp_omp.c.s
.PHONY : lbp_omp.s

# target to generate assembly for a file
lbp_omp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_omp.dir\build.make CMakeFiles/lbp_omp.dir/lbp_omp.c.s
.PHONY : lbp_omp.c.s

lbp_seq.obj: lbp_seq.c.obj
.PHONY : lbp_seq.obj

# target to build an object file
lbp_seq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_seq.dir\build.make CMakeFiles/lbp_seq.dir/lbp_seq.c.obj
.PHONY : lbp_seq.c.obj

lbp_seq.i: lbp_seq.c.i
.PHONY : lbp_seq.i

# target to preprocess a source file
lbp_seq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_seq.dir\build.make CMakeFiles/lbp_seq.dir/lbp_seq.c.i
.PHONY : lbp_seq.c.i

lbp_seq.s: lbp_seq.c.s
.PHONY : lbp_seq.s

# target to generate assembly for a file
lbp_seq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_seq.dir\build.make CMakeFiles/lbp_seq.dir/lbp_seq.c.s
.PHONY : lbp_seq.c.s

util.obj: util.c.obj
.PHONY : util.obj

# target to build an object file
util.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_seq.dir\build.make CMakeFiles/lbp_seq.dir/util.c.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_omp.dir\build.make CMakeFiles/lbp_omp.dir/util.c.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IO_test.dir\build.make CMakeFiles/IO_test.dir/util.c.obj
.PHONY : util.c.obj

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_seq.dir\build.make CMakeFiles/lbp_seq.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_omp.dir\build.make CMakeFiles/lbp_omp.dir/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IO_test.dir\build.make CMakeFiles/IO_test.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_seq.dir\build.make CMakeFiles/lbp_seq.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lbp_omp.dir\build.make CMakeFiles/lbp_omp.dir/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\IO_test.dir\build.make CMakeFiles/IO_test.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... IO_test
	@echo ... lbp_omp
	@echo ... lbp_seq
	@echo ... IO_test.obj
	@echo ... IO_test.i
	@echo ... IO_test.s
	@echo ... lbp_omp.obj
	@echo ... lbp_omp.i
	@echo ... lbp_omp.s
	@echo ... lbp_seq.obj
	@echo ... lbp_seq.i
	@echo ... lbp_seq.s
	@echo ... util.obj
	@echo ... util.i
	@echo ... util.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

